name: build

on:
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USERNAME: horizon233 # 量替换为你的 DockerHub 用户名

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/386,linux/amd64,linux/arm64
          tags: ${{ env.DOCKERHUB_USERNAME }}/githubflow-demo:${{ steps.vars.outputs.sha_short }}